name: ll-cpp-linter
channels:
  - conda-forge
dependencies:
  - clang-tools >=17.0.6
  - clangxx >=17.0.6
  - cmake >=3.20
  - cxx-compiler
  - gtest >=1.14.0
  - make
  - protobuf >=4.25.2
  - rapidcheck >=2023.4.13
  - yaml-cpp >=0.8.0
