name: ll-cpp-docs
channels:
  - conda-forge
dependencies:
  - cmake >=3.20
  - cxx-compiler
  - doxygen >=1.10.0
  - graphviz >=9.0.0
  - gtest >=1.14.0
  - make
  - protobuf >=4.25.2
  - rapidcheck >=2023.4.13
  - yaml-cpp >=0.8.0
  - zlib
